spring.application.name=url-shortener-be
server.port=8181

spring.datasource.url=jdbc:mysql://localhost:3306/urlshortnerdb
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=e0855853fc9d9d623d08b112283e0eb99bdc76b8774c2faef687feb04b9e4d37ce2a4de967386ee6f16bac02680d4799a2d45ac68b1a1907ff231981fc1c3d82
jwt.expiration=17200000